services:
  app:
    container_name: ahr999-chart
    image: ahr999-chart:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT:-5200}:8080"
    restart: unless-stopped
